apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-agent-config
  namespace: {{ .Release.Namespace }}
data:
  config-init.hcl: |
    vault {
      address = "{{ .Values.vault.address }}"
      tls_skip_verify = true
      tls_ca_cert     = "/vault/custom/vault-client-cert/ca.crt"
      tls_cert_file   = "/vault/custom/vault-client-cert/client.crt"
      tls_key_file    = "/vault/custom/vault-client-cert/client.key"
    }

    exit_after_auth = true

    auto_auth {
      method {
        type = "kubernetes"
        mount_path = "auth/kubernetes"
        config = {
          role = "{{ .Values.vault.role }}"
        }
      }
      sink {
        type = "file"
        config = {
          path = "/home/vault/.vault-token"
        }
      }
    }

    template {
      destination = "/vault/secrets/config"
      perms       = 0644
      contents    = <<EOT
    {{`{{- with secret "`}}{{ .Values.vault.path | default (printf "dev/data/%s-%s" (default .Chart.Name .Values.fullnameOverride | default .Values.nameOverride) .Release.Namespace) }}{{`" -}}`}}
    {{`{{- printf "%s" (base64Decode (index .Data.data "`}}{{ .Values.vault.key | default (default .Chart.Name .Values.fullnameOverride | default .Values.nameOverride) }}{{`")) }}`}}
    {{`{{- end }}`}}
    EOT
    }

